# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssd/protos/anchor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssd/protos/anchor.proto',
  package='object_detection.protos',
  serialized_pb=_b('\n\x17ssd/protos/anchor.proto\x12\x17object_detection.protos\"I\n\x08\x41nAnchor\x12\x0b\n\x03src\x18\x01 \x02(\t\x12\x14\n\x0c\x61spect_ratio\x18\x02 \x03(\x02\x12\x1a\n\x0c\x65xtra_anchor\x18\x03 \x01(\x08:\x04true')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ANANCHOR = _descriptor.Descriptor(
  name='AnAnchor',
  full_name='object_detection.protos.AnAnchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='object_detection.protos.AnAnchor.src', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aspect_ratio', full_name='object_detection.protos.AnAnchor.aspect_ratio', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extra_anchor', full_name='object_detection.protos.AnAnchor.extra_anchor', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['AnAnchor'] = _ANANCHOR

AnAnchor = _reflection.GeneratedProtocolMessageType('AnAnchor', (_message.Message,), dict(
  DESCRIPTOR = _ANANCHOR,
  __module__ = 'ssd.protos.anchor_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.AnAnchor)
  ))
_sym_db.RegisterMessage(AnAnchor)


# @@protoc_insertion_point(module_scope)
